export const EGYPTIAN_GOVERNORATES: string[] = [
  'Cairo (القاهرة)',
  'Giza (الجيزة)',
  'Alexandria (الإسكندرية)',
  'Qalyubia (القليوبية)',
  'Gharbia / Tanta & Zifta (الغربية وطنطا وزفتى)',
  'Dakahlia / Mansoura (الدقهلية والمنصورة)',
  'Sharqia / Zagazig (الشرقية والزقازيق)',
  'Monufia (المنوفية)',
  'Beheira (البحيرة)',
  'Kafr El Sheikh (كفر الشيخ)',
  'Damietta (دمياط)',
  'Port Said (بورسعيد)',
  'Ismailia (الإسماعيلية)',
  'Suez (السويس)',
  'South Sinai / Sharm El Sheikh (جنوب سيناء وشرم الشيخ)',
  'Red Sea / Hurghada & Gouna (البحر الأحمر والغردقة والجونة)',
  'North Sinai (شمال سيناء)',
  'Matrouh & North Coast (مطروح والساحل الشمالي)',
  'Faiyum (الفيوم)',
  'Beni Suef (بني سويف)',
  'Minya (المنيا)',
  'Asyut (أسيوط)',
  'Sohag (سوهاج)',
  'Qena (قنا)',
  'Luxor (الأقصر)',
  'Aswan (أسوان)',
  'New Valley (الوادي الجديد)'
];
